### ISSUE TITLE
你好，请问是高清直播源吗？

### ISSUE THREAD

**Issue by bike3097a** [nczyw/iptv#1]

**Comment by nczyw** [comment]
全是高清，5月份从机顶盒抓的

**Comment by bike3097** [comment]
可以，部分台看不了，不知道啥情况

**Comment by nczyw** [comment]
> 可以，部分台看不了，不知道啥情况

比如说是什么台呢？我可以去看看最新地址是否有变化

**Comment by bike3097** [comment]
还少本地台，南京十八频道，南京综合频道等，都没有。

**Comment by bike3097** [comment]
昨天测试，你目前的源又可以了，唯独频道少了不少

**Comment by bike3097** [comment]
#EXTINF:-1,南京综合
http://192.168.2.1:4022/udp/239.49.0.25:8192
#EXTINF:-1,南京生活
http://192.168.2.1:4022/udp/239.49.0.184:9438
#EXTINF:-1,南京信息
http://192.168.2.1:4022/udp/239.49.0.75:8000
#EXTINF:-1,南京影视
http://192.168.2.1:4022/udp/239.49.0.24:8000
#EXTINF:-1,南京娱乐
http://192.168.2.1:4022/udp/239.49.0.38:8000
#EXTINF:-1,南京少儿
http://192.168.2.1:4022/udp/239.49.0.45:8000
#EXTINF:-1,十八频道
http://192.168.2.1:4022/udp/239.49.0.26:8200

**Comment by bike3097** [comment]
把我提供的添加进去

**Comment by bike3097** [comment]
要么你在重新抓下包看看，能不能抓到最新的，麻烦你了。

**Comment by nczyw** [comment]
> 要么你在重新抓下包看看，能不能抓到最新的，麻烦你了。

年后，最新的已经没有地方台了，年前还能抓到的地方台；
我在无锡，我家电视盒子，开机的台，只有github上面的内容了，南京盒子，还能看地方台吗？盒子开机，运营商会下发一个播放列表，可以看到还有哪些台的。

**Comment by bike3097** [comment]
好的，目前抓不到了，是吧。南京盒子可以看地方台。

**Comment by nczyw** [comment]
> 好的，目前抓不到了，是吧。南京盒子可以看地方台。

盒子能看，就简单了，你把交换机插在IPTV口上，交换机一个口插电脑，一个口插盒子，打开 Wireshark ，选择网卡，打开盒子，你看直播的时候会一直出现UDP那个通信，就是组播，能看到每个台的地址;
[IPTV抓包方法](https://blog.csdn.net/nczywq/article/details/136990185)

**Comment by bike3097** [comment]
我这边抓不了，希望您有空再抓一次，分享下，谢谢

**Comment by nczyw** [comment]
> 我这边抓不了，希望您有空再抓一次，分享下，谢谢
我所在地区，IPTV没有城市的地方台，电视盒子观看时，也没有，已经把你提供的南京地方台，添加到m3u文件中，谢谢
